DefaultSettings:
  orgId: ''
  orgUrl: ''
  widgetId: ''
  authUrl: ''
UnauthenticatedChat:
UnauthenticatedChatWithTyping:
UnauthenticatedChatWithTranscripts:
UnauthenticatedChatWithAttachments:
UnauthenticatedChatWithPrechat:
UnauthenticatedChatOutsideOfOperatingHours:
UnauthenticatedChatWithChatReconnect:
UnauthenticatedChatWithMasking:
AuthenticatedChat:
  orgId: ''
  orgUrl: ''
  widgetId: ''
  authUrl: ''