DefaultSettings:
  orgId: ''
  orgUrl: ''
  widgetId: ''
  authUrl: ''
UnauthenticatedChat:
UnauthenticatedChatWithTyping:
UnauthenticatedChatWithTranscripts:
UnauthenticatedChatWithAttachments:
UnauthenticatedChatWithPrechat:
UnauthenticatedChatOutsideOfOperatingHours:
UnauthenticatedChatWithChatReconnect:
UnauthenticatedChatWithMasking:
UnauthenticatedChatWithNoEscalationToVoiceAndVideo:
AuthenticatedChat:
  orgId: ''
  orgUrl: ''
  widgetId: ''
  authUrl: ''
AuthenticatedChatWithTyping:
AuthenticatedChatWithTranscripts:
AuthenticatedChatWithNoEscalationToVoiceAndVideo:
AuthenticatedChatWithAttachments:
AuthenticatedChatWithPrechat:
AuthenticatedChatWithChatReconnect:
AuthenticatedChatWithPersistentChat:
AuthenticatedChatWithMasking:
AuthenticatedChatWithPersistentChatWithoutReconnect: